<a href="https://colab.research.google.com/github/TamyBuenafe/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Problem 1. Student A, Student B, and Student C have a total of Php 89 cash in their banks. Student A has 6 less than Student C. Student B has 3 times what Student C has. How much does each student have? (30 points)

In [50]:
equation1 = np.array([[1,1,1],[1,0,4],[0,0,5]])
equation2 = np.array([[89],[89],[95]])
amount = np.linalg.inv(equation1).dot(equation2)
print(amount)

[[13.]
 [57.]
 [19.]]


Problem 2. Solve each system: (30 points)

3x - y + z = 5

9x - 3y +3z = 15

-12x +4y -4z = -20 

In [49]:
import numpy as np

mat1 = np.array([[3,-1,1],[9,3,3],[-12,4,-4]])
mat2 = np.array([[5],[15],[20]])
x = np.linalg.solve(mat1,mat2) # i already used every method i can used in finding the answer of this problem. it because When a Linear Algebra-related circumstance prevents continued accurate execution of the function, this exception class is raised programmatically in linalg functions.

print(x)

LinAlgError: ignored

Problem 3. Consider the matrix, (40 points)



In [ ]:
import numpy as np
from numpy.linalg import eig



E = np.array ([[8,5,-6],[-12,-9,12],[-3,-3,5]])
print (E)

s,t = np.linalg.eig(E)
print ("The eigenvalue/s is /are:",s)
print ("The eigenvectors are:",t)


[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The eigenvalue/s is /are: [-1.  3.  2.]
The eigenvectors are: [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
