<a href="https://colab.research.google.com/github/TamyBuenafe/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Question 1. Create a Python code that displays a square matrix whose length is 5 (10 points)

In [24]:
import numpy as np
b = np.full((5,5),5)
print(b)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


Question 2. Create a Python code that displays a square matrix whose elements below the principal diagonal are zero (10 points)



In [16]:
import numpy as np
x = np.diag([1, 2, 3, 4 ,5])
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


Question 3. Create a Python code that displays a square matrix which is symmetrical (10 points)

Question 4. What is the inverse of matrix C? Show your solution by python coding. (20 points)

In [4]:
C = np.array([[1,2,3],[2,3,3],[3,-4,2]])
print(A)
inv_C=np.linalg.inv(C)
print(inv_C)

[[ 5  4  3]
 [10  9  4]
 [10 13 15]]
[[-0.7826087   0.69565217  0.13043478]
 [-0.2173913   0.30434783 -0.13043478]
 [ 0.73913043 -0.43478261  0.04347826]]


Question 5. What is the determinant of the given matrix in Question 4? Show your solution by python coding. (20 points)

In [5]:
import numpy as np
C = np.array([[1,2,3],[2,3,3],[3,-4,2]])
print(C)
print(np.linalg.det(C))
print(round(np.linalg.det(C)))

[[ 1  2  3]
 [ 2  3  3]
 [ 3 -4  2]]
-23.0
-23


Question 6. Find the roots of the linear equations by showing its python codes (30 points)

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [2]:
import numpy as np
A = np.array([[5,4,3],[10,9,4],[10,13,15]])
print(A)
inv_A=np.linalg.inv(A)
print(inv_A)
B= np.array([[3.4],[8.8],[19.2]])
print(B)

#AA^-1x = B.A^-1
X = np.dot(inv_A,B)
print(X)

[[ 5  4  3]
 [10  9  4]
 [10 13 15]]
[[ 0.87368421 -0.22105263 -0.11578947]
 [-1.15789474  0.47368421  0.10526316]
 [ 0.42105263 -0.26315789  0.05263158]]
[[ 3.4]
 [ 8.8]
 [19.2]]
[[-1.19789474]
 [ 2.25263158]
 [ 0.12631579]]
