<a href="https://colab.research.google.com/github/TamyBuenafe/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Problem 1


In [ ]:
import numpy as np
W = np.array([[1,-3],[2,-2],[3,1]])
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
Y = np.array([[1,2,0],[0,-1,2]])
Z = np.array([[0,1],[2,3]])

In [27]:

W = np.array([[1,-3], [2,-2], [3,1]])
Y = np.array([[1,2,0], [0,-1,2]])
np.dot (W,Y)

array([[ 1,  5, -6],
       [ 2,  6, -4],
       [ 3,  5,  2]])

In [18]:
#b. Z+Z
 
Z = np.array([[0,1],[2,3]])
Z = np.array([[0,1],[2,3]])
print(Z+Z)

[[0 2]
 [4 6]]


In [36]:
#c. 3X
X = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
S = 3*X
print(S)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


#Problem 2


In [47]:
#a. The product (YW)2 is not defined
seta = np.dot(Y,W) 
print(seta)


[[ 5 -7]
 [ 4  4]]


In [29]:
#b. WY – X =
WY = np.array([[1,5,-6],[2,6,-4],[3,5,2]])
X  = np.array([[3,2,1],[-1,2,3],[2,-1,1]])
print(WY-X) #Therefore the statement is true 



[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]


C.YW – Z^2

In [48]:
A = (seta)
B = np.square(Z)
print (A-B)

[[  5  -8]
 [-12 -77]]
