<a href="https://colab.research.google.com/github/TamyBuenafe/Linear-Algebra-58020/blob/main/PrelimExam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#PRELIM EXAM

Question 1. (20 points) Create a 4 x 4 matrix whose diagonal elements are all one (1's). Name it as matrix "C". Show your solutions using Python codes and do not forget to label them on the Text Cell.




In [ ]:
import numpy as np
#Create a diagonal matrix
C = np.diagonal([[1,1,1,1],[1,1,1,1],[1,1,1,1],[1,1,1,1]])
print (C)

[1 1 1 1]


Question 2. (20 points) In relation to Question 1, show a solution that doubles all the values of each element. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [6]:
output = np.square(C)
print(output) 

[1 1 1 1]


Question 3. (10 points) Find the cross-product of matrices, A = [2,7,4] and

B = [3,9,8]. Show your solutions using Python codes and do not forget to label them on the Text Cell.

In [ ]:
import numpy as np
a =np.array ([2,7,4]) #First Value 
b =np.array ([3,9,8]) #Second Value 
print (a)
print (b)




[2 7 4]
[3 9 8]


In [ ]:
c = np.cross(a,b) 
print (c)

[20 -4 -3]
