<a href="https://colab.research.google.com/github/TamyBuenafe/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Vector Space and its Operations





In [8]:

import numpy as np 
a = np.array([4,3])
b = np.array([2,-5])
print('Vector a is', a)
print("Vector b is" , b)

Vector a is [4 3]
Vector b is [ 2 -5]


In [17]:
ball1 = np.array([1,2,3])
ball2 = np.array([0,1,-1])

pool = np.array([ball1,ball2])
print(pool.shape)
print(pool.size)
print(pool.ndim)


(2, 3)
6
2


In [19]:
R = a+b
print(R)

[ 6 -2]


In [20]:
R = np.add(a,b)
R

array([ 6, -2])

##Vector subtraction




In [21]:
R = np.subtract(a,b)
R

array([2, 8])

#Vector Scaling

In [23]:
a = np.array([1,5,8,9])
S = 5*a
print(S)

[ 5 25 40 45]


In [25]:
S = np.multiply(5,a)
print(S)

[ 5 25 40 45]


##Vector Cross Product

In [30]:
import numpy as np
#initiallize arrays
A = np.array([2,7])
B = np.array([1,7])

S = np.cross(A,B)
print(S)

7


In [31]:
S = np.dot(A,B)
print(S)

51
