<a href="https://colab.research.google.com/github/TamyBuenafe/Linear-Algebra-58020/blob/main/Vector_Representation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Matrix and its Operation

In [1]:
import numpy as np
#Create a 1x3 array 
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
#Create a 2x2 array
b = np.array([[1,2,3],[4,5,6]]) 
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#Create a 3x3 matrix
c = np.array ([[1,2,3],[4,5,6],[7,8,9]]) 
print(c)
      

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#Create a constant array with all value are 6
d = np.full ((4,4),6)
print(d)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [9]:
#Create a diagonal matrix 
e = np.array ([[1,2,3],[4,5,6],[7,8,9]]) 
print(e)
e = np.diagonal([[1,2,3],[4,5,6],[7,8,9]] )
print(e)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 5 9]


In [10]:
#Create an identity matrix 
f = np.eye(9)
print(f)

[[1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [13]:
#Create a zero matrix
g = np.zeros((4,5))
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
#Create an empty matrix
h = np.empty((0,5))
print(h)

[]


In [15]:
#Addition of Matrices
i = np.array([[1,2,3],[4,5,6]]) 
j = np.zeros ((2,3))
print(i+j)

[[1. 2. 3.]
 [4. 5. 6.]]


In [16]:
#Subtraction of Matrices
i = np.array([[1,2,3],[4,5,6]])
j = np.array([[-1,2,4],[6,4,2]])  
print(i-j)

[[ 2  0 -1]
 [-2  1  4]]
